# Generated by Django 4.0.6 on 2022-07-15 15:57

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=200, unique=True, verbose_name='Tier name')),
                ('original_link', models.BooleanField(default=False, help_text='User can generate originally uploaded image', verbose_name='Original image')),
                ('thumbnail_sizes', models.CharField(help_text='Format: number, number | e.g. 200, 400', max_length=200, verbose_name='Sizes of thubnails')),
                ('expiring_link', models.BooleanField(default=False, help_text='User can generate expiring links', verbose_name='Expiring links')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png'])])),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tier'),
        ),
    ]
