# Generated by Django 4.0.6 on 2022-07-14 20:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=200, unique=True, verbose_name='Tier name')),
                ('original_link', models.BooleanField(default=False, help_text='User can generate originally uploaded image', verbose_name='Original image')),
                ('thumbnail_sizes', models.CharField(max_length=200, verbose_name='Sizes of thubnail')),
                ('expiring_link', models.BooleanField(default=False, help_text='User can generate expiring links', verbose_name='Expiring links')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tier')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png'])])),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
