# Generated by Django 4.0.6 on 2022-07-15 15:57

from django.db import migrations


def basic_tier(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Tier = apps.get_model("api", "Tier")
    db_alias = schema_editor.connection.alias
    Tier.objects.using(db_alias).bulk_create(
        [
            Tier(tier_name="Basic", thumbnail_sizes=200),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(basic_tier),
    ]
